# Sobre os autores {-}

## Alessandro Samuel-Rosa {-}

Alessandro estudou Ciência do Solo e trabalha na Universidade Federal de Santa Maria (UFSM) desde o final de 
2016. Após seus primeiros trabalhos sobre as interações entre o uso da terra e a qualidade do solo na UFSM, em
2012 mudou para o campo da Pedometria. A colaboração com pesquisadores do Centro Nacional de Pesquisas sobre
Solos (Embrapa), do International Soil Reference and Information Centre (ISRIC), da Wageningen University and
Research Centre (WUR) e da Universidade Federal Rural do Rio de Janeiro (UFRRJ) permitiu-lhe dominar múltiplos
métodos e técnicas pedométricas. Seu principal interesse científico é a modelagem espacial do solo com foco em
estratégias de amostragem, seleção e calibração de modelos e análise de incerteza. Alessandro publicou 
recentemente alguns artigos relevantes sobre esses tópicos em revistas internacionais. Alessandro também é o
autor de dois pacotes para o R, os quais são amplamente utilizados, cada um com mais de 200 downloads por mês.
(Saiba mais [aqui](http://lattes.cnpq.br/1609751519717461))

## Ricardo S. D. Dalmolin {-}

Ricardo possui graduação e mestrado em Agronomia pela UFSM e doutorado em Ciências do Solo pela Universidade
Federal do Rio Grande do Sul (UFRGS). Atualmente é professor associado da UFSM, atuando no Programa de
Pós-Graduação em Ciência do Solo (PPGCS) e no Programa Pós-Graduação em Educação Ambiental. Ricardo é 
consultor de diversas revistas científicas e líder do Grupo de Pesquisa do CNPq *Gênese, composição e
comportamento dos solos do RS*. Ricardo tem experiência na área ambiental e agronômica, com ênfase em gênese, 
morfologia e classificação do solo, atuando principalmente nos temas 'levantamento de solos', 'classificação 
de solos', 'aptidão de uso das terras', 'sensoriamento remoto' e 'mapeamento digital de solos'. Ainda foi 
presidente do Núcleo Regional Sul da Sociedade Brasileira de Ciência do Solo, membro do Conselho Diretor da
Sociedade Brasileira de Ciência do Solo, e responsável pelo Museu de Solos do RS. (Saiba mais 
[aqui](http://lattes.cnpq.br/3735884911693854))

## Paulo I. Gubiani {-}

Paulo possui graduação em Agronomia, e mestrado e doutorado em Ciência do Solo pela UFSM, tendo sido foco de
sua formação acadêmica o estudo da compactação do solo e seu efeito sobre o desenvolvimento e produtividade 
das culturas agrícolas. Atualmente Paulo é professor da área de Física do Solo na UFSM, desenvolvendo estudos, 
principalmente, sobre os seguintes temas: 'estrutura do solo', 'compactação do solo', 'compressibilidade do
solo', 'relação entre propriedades físicas do solo e crescimento de plantas' e 'balanço hídrico'. Paulo também
tem grande experiência no uso e desenvolvimento de aplicativos em VBA para planilhas eletrônicas como o 
Microsoft Office Excel. Recentemente, Paulo publicou importante revisão bibliográfica sobre indicadores 
físicos de qualidade do solo, numa tentativa de apontar para novos caminhos para a pesquisa em Física do Solo
no Brasil. (Saiba mais [aqui](http://lattes.cnpq.br/7251203817503318))

## Diego J. Gris {-}

Diego é acadêmico do curso de Agronomia da Universidade Federal de Santa Maria (UFSM). Bolsista de Iniciação
Científica no grupo de Pedologia da UFSM. Estudou por um ano (2013) na Cornell University - EUA, com bolsa de
graduação sanduíche (CAPES) do programa Ciência sem Fronteiras. 
(Saiba mais [aqui](http://lattes.cnpq.br/0248016063663067))

## Nicolas A. Rosin {-}

Nícolas é acadêmico do curso de Agronomia na Universidade Federal de Santa Maria (UFSM) e bolsista de 
Iniciação Científica no Laboratório de Pedologia, atuando na área de levantamento e classificação de solos, 
assim como pedometria. Possui experiência na área da Agronomia com ênfase em Ciência do Solo.
(Saiba mais [aqui](http://lattes.cnpq.br/8013808194359269))
