# Conjunto de dados

<!-- ## Tabela *dataset* -->

A maximização da disseminação e uso de um conjunto de dados, o apropriado reconhecimento de seus autores ou 
autoras e instituição responsável, bem como a identificação que alterações e ajustes feitos após a publicação
da sua primeira versão, dependem da provisão de dados mínimos sobre aquele conjunto de dados. No Fe-BR esses
dados são inseridos na tabela denominada *dataset*.

Por conter dados essenciais sobre um conjunto de dados, a tabela *dataset* é sempre a primeira a ser revisada 
e processada. Quaisquer dados faltantes são solicitados aos autores/responsáveis pelo conjunto de dados. Da 
mesma forma, sempre que dados incoerentes são identificados, os autores/responsáveis pelo conjunto de dados
são consultados iterativamente até que quaisquer dúvidas sejam completamente sanadas. O devido preenchimento
da tabela *dataset* é essencial para o posterior processamento dos dados e metadados de um conjunto de dados
de ferro do solo.

A tabela *dataset* possui cerca de vinte itens estruturados em uma sequência de linhas. Os dados sobre o
conjunto de dados são inseridos na segunda coluna, imediatamente ao lado da sua respectiva identificação e 
definição contidas na primeira coluna. A primeira linha é dedicada à identificação propriamente dita do 
conjunto de dados no Fe-BR, a segunda ao título do conjunto de dados, e assim por diante, até as últimas 
linhas, dedicadas aos termos usados para a descrição de características chave e indexação do conjunto de 
dados.

item              | dado
----------------- | -----
dataset_id        | ...
dataset_titulo    | ...
dataset_descricao | ...
...               | ...
palavras_chave    | ...
categoria_vcge    | ...

Os itens da tabela *dataset* são descritos em detalhe a seguir.


## Identificação
<!-- ## `dataset_id` -->

Código identificador único do conjunto de dados. Esse código é usado para identificar cada uma dos conjuntos 
de dados incluídos no Fe-BR. Em geral, o código de identificação de um novo conjunto de dados inserido no 
Fe-BR é definido pela sua posição (ordem das contribuições) em relação aos demais conjunto de dados já 
inseridos no Fe-BR. Por exemplo, o código de identificação do primeiro conjunto de dados contribuído (`ctb`) 
para o Fe-BR é `dataset_id = ctb0001`.

No caso dos conjuntos de dados obtidos diretamente do Sistema de Informação de Solos Brasileiros
([SISB](https://www.sisolos.cnptia.embrapa.br/)), o código de identificação utilizado no Fe-BR é o mesmo usado
naquele sistema. Isso possibilita estabelecer comunicação direta do SISB com o Fe-BR, o que permite atualizar 
os dados do primeiro caso ajustes nos dados sejam feitos durante o seu processamento no Fe-BR.

<!-- ## `dataset_titulo` -->

Título do conjunto de dados, geralmente relacionado ao título do projeto, tese, dissertação, etc que o gerou. 
Preferência é dada ao uso de título específico para o conjunto de dados, o que identifica melhor o seu 
conteúdo do que o título do trabalho ou projeto que o gerou. Isso é importante para aumentar as chances de o
conjunto de dados ser identificado em ferramentas de busca e assim potencializar o seu reuso.

Quanto à formatação do título, usa-se a mesma língua da fonte -- apesar de títulos em língua portuguesa serem 
preferidos -- e caracteres em caixa baixa, com exceção da primeira letra do título e dos nomes próprios. Por 
exemplo, *Conjunto de dados da tese 'Matéria orgânica e características físicas, químicas, mineralógicas e 
espectrais de Latossolos de diferentes ambientes'*.

## Descrição {#descricao}
<!-- ## `dataset_descricao` {#descricao} -->

Descrição do conjunto de dados, contendo dados básicos para maximizar o reuso futuro do conjunto de dados sem
que seja necessário entrar em contato com os seus autores/responsáveis. A descrição do conjunto de dados 
inclui aspectos como:

1. Os motivos para a realização do estudo que levou à geração dos dados,
2. Um resumo dos dados incluídos no conjunto de dados e dos métodos analíticos usados, e
3. Uma descrição do delineamento amostral e a forma de coleta das amostras.

A descrição do delineamento amostral, ou seja, a estratégia utilizada para seleção dos locais de observação e
amostragem do solo, fornece os elementos necessários para determinar se -- e como -- os diferentes conjuntos 
de dados podem -- ou devem -- ser utilizados em uma determinada aplicação.

Quando for o caso, a descrição do conjunto de dados deve incluir também:

1. Os motivos para a presença de camadas/horizontes com dados faltantes para uma ou mais variáveis do solo, e
2. Uma descrição das alterações/modificações realizadas quando da publicação de uma nova versão.

Uma descrição exemplar de um conjunto de dados é a que segue:

> Conjunto de dados produzido como parte da Dissertação submetida como requisito parcial para obtenção do grau
de Mestre no Curso de Pós-Graduação em Agronomia da Universidade Federal Rural do Rio de Janeiro. Inclui dados
do conteúdo de ferro total determinado via extração com solução de ácido sulfúrico para 20 perfis do solo
observados no município de Pinheiral (RJ). A seleção dos locais de observação foi feita com base no 
conhecimento pedogenético da área de estudo, a partir de informações prévias sobre o meio físico e solo, tendo
sido selecionados pontos representativos que contemplassem a variação dos fatores de formação do solo. Em cada
local foram abertas trincheiras para descrição dos perfis e coleta de amostras dos horizontes para 
caracterização do solo segundo procedimentos descritos no Manual de Descrição e Coleta de Solo no Campo 
(Santos et al., 2013). Devido à existência de limitações orçamentárias, apenas amostras de horizontes
selecionados foram submetidas à determinação do conteúdo de ferro total. Em alguns casos, apenas os horizontes 
B diagnósticos foram analisados, em outros o primeiro horizonte A e um ou mais horizontes subsuperficiais.

## Versionamento {#versao}
<!-- ## `dataset_versao` {#versao} -->

Versão do conjunto de dados. Dado necessário para identificar os casos em que o conjunto de dados foi
modificado por uma razão técnica e/ou científica. Por exemplo, um conjunto de dados contendo inúmeros perfis
do solo, cujas localizações originais não foram georreferenciadas -- `dataset_versao = 1` --, é modificado
consideravelmente de maneira que todos os perfis do solo possuam coordenadas espaciais aproximadas dos locais 
de observação -- `dataset_versao = 2`.

Sempre que uma nova versão de um conjunto de dados é preparada, uma descrição sumária das modificações deve 
ser incluída na descrição do conjunto de dados em `dataset_descricao`. Os responsáveis pelas modificações 
devem ser identificados conforme descrito [abaixo](#contribuidor).

<!-- ## `publicacao_data` -->

Data de publicação do conjunto de dados. A data de publicação do conjunto de dados não é necessariamente a 
mesma data de publicação do trabalho que o gerou ou utilizou pela primeira vez, mas sim a data em que o 
conjunto de dados foi tornado efetivamente público e disponível para acesso. Quando modificações são feitas
no conjunto de dados durante ou após a sua inserção no Fe-BR, resultando assim em uma nova versão, então a 
data de publicação é a data em que essa nova do conjunto de dados foi disponibilizada no Fe-BR.

A data de publicação é apresentada na sequência dia, mês e ano, usando formato numérico dd-mm-aaaa ou 
dd/mm/aaaa, ou seja, dois dígitos para o dia e mês, e quatro dígitos para o ano. Preferência é dada à inserção
dos dados de ambos dia, mês e ano. Contudo, dentre os três dados, o mais importante é aquele relativo ao ano.
Quando algum dos dados não é conhecido, usa-se o símbolo `xx` em substituição. Caso a data de publicação do 
conjunto de dados seja completamente desconhecida, usa-se a data de publicação do trabalho que o gerou ou 
utilizou pela primeira vez.

## Licença de uso {#licenca}
<!-- ## `dataset_licenca` {#licenca} -->

Licença de uso do conjunto de dados. Dado que define como o conjunto de dados pode ser usado a partir da sua
publicação no Fe-BR.

A legislação brasileira ainda não especifica, exatamente, qual deve ser a licença de uso dos conjuntos de 
dados gerados por projetos mantidos via financiamento público. Contudo, existe algum
[consenso](http://wiki.dados.gov.br/Produto-GT1-Levantamento-Juridico-Licenciamento-Dados-Abertos.ashx) de que
uma licença de uso apropriada para esse tipo de conjuntos de dados é a licença Creative Commons 
[CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/). A licença CC-BY 4.0 permite que um conjunto de 
dados seja distribuido, remixado, adaptado e usado para criar outros produtos, mesmo que para fins comerciais, 
desde que seja atribuido o devido crédito aos autores/responsáveis pelo conjunto de dados original. Assim, 
trata-se de uma das licença mais flexível dentre as licenças Creative Commons disponíveis, maximizando a
disseminação e uso dos conjuntos de dados. Assim, a licença CC-BY 4.0 é a licença padrão do Fe-BR. Maiores
informações sobre as licenças de uso recomendadas para conjuntos de dados públicos podem ser encontradas no
[fórum](https://groups.google.com/forum/#!forum/inda-br) da Infraestrutura Nacional de Dados Abertos (INDA).

Para os conjuntos de dados gerados por projetos mantidos via financiamento privado, onde as partes envolvidas
têm interesse em compartilhar os dados desde que não para fins comerciais, recomenda-se usar a licença 
Creative Commons [CC-BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/). A licença CC-BY-NC 4.0 
possui praticamente os mesmos termos da licença CC-BY 4.0, exceto pelo fato de que a distribuição, remixação, 
adaptação e derivação de outros produtos não podem ser usados para fins comerciais.

## Instituição
<!-- ## `organizacao_<...>` -->

Identificação e endereços físico e eletrônico da organização responsável pela geração do conjunto de dados. 
Quando o conjunto de dados é provido por organização outra que não aquela responsável pela sua geração, 
pode-se optar por identificar a organização que atualmente detém responsabilidade técnica sobre o conjunto de
dados, ou seja, a organização provedora do conjunto de dados. Isso é especialmente importante caso 
modificações consideráveis tenham sido feitas nos dados. O mesmo pode ser aplicado aos conjuntos de dados
gerados por duas ou mais organizações. No caso de conjuntos de dados gerados ou sob responsabilidade de 
organizações como a Embrapa, que possuem várias unidades, identifica-se a unidade da organização responsável 
pelo conjunto de dados, nunca apenas a organização. Em todo caso, é fundamental que ambos endereço físico e
eletrônico sejam válidos e atuais.

Os dados necessários para a indentificação da organização responsável pelo conjunto de dados são os seguintes:

* `organizacao_nome`, o nome da organização,
* `organizacao_url`, o endereço da organização na Internet,
* `organizacao_pais_id`, o país da organização,
* `organizacao_municipio_id`, a cidade da organização,
* `organizacao_codigo_postal`, o código postal da organização,
* `organizacao_rua_nome`, a rua da organização,
* `organizacao_rua_numero`, o número da organização em sua rua.

## Autoria {#autor}
<!-- ## `autor_<...>` {#autor} -->

Identificação dos autores ou responsáveis pela geração do conjunto de dados. Quando o acesso aos autores é
impossível ou limitado, identifica-se as pessoas que atualmente detém responsabilidade técnica sobre o 
conjunto de dados. No caso de trabalhos acadêmicos, como monografias, dissertações e teses, identifica-se o 
autor e o orientador principal do trabalho acadêmico.

Os dados necessários para a indentificação dos autores do conjunto de dados são os seguintes:

* `autor_nome`, o nome completo dos autores, e
* `autor_email`, o endereço de e-mail atual dos autores. 

Sempre que um conjunto de dados tiver dois ou mais autores, insere-se os respectivos dados de identificação 
separados por ponto e vírgula. É importante que o endereço de e-mail dos autores do conjunto de dados seja 
válido e atual. Isso é fundamental para permitir o contato com os autores sempre que surgirem dúvidas sobre o
conjunto de dados. O conhecimento do nome completo dos autores também é fundamental para permitir os devidos 
[créditos](#licenca) lhes sejam atribuídos sempre que o conjunto de dados for distribuido, remixado, adaptado
ou usado para criar outros produtos.

## Contribuições {#contribuidor}
<!-- ## `contribuidor_<...>` {#contribuidor} -->

Identificação dos autores ou responsáveis por modificações no conjunto de dados. Modificações constituem
contribuições à melhoria do conjunto de dados, sendo assim apresentadas na sua [descrição](#descricao) e 
geralmente resultando em uma nova [versão](#versao) do conjunto de dados. Como a inserção de um conjunto de
dados no Fe-BR sempre requer algum tipo de modificação, os integrantes da equipe do Fe-BR sempre figuram como
autores de contribuições à sua melhoria.

Os dados necessários para a indentificação dos responsáveis pelas modificações feitas num conjunto de dados 
são os seguintes:

* `contribuidor_nome`, o nome dos autores das modificações,
* `contribuidor_email`, o endereço de e-mail atual dos autores das modificações, e
* `contribuidor_organizacao`, a organização à qual os autores das modificações estão afiliados.

A apropriada identificação dos autores das modificações no conjunto de dados é fundamental para permitir o 
contato com os mesmos sempre que surgirem dúvidas sobre as novas versões do conjunto de dados. Além disso, 
permite atribuir o devido crédito quando se deseja referenciar uma versão específica do conjunto de dados. 
Contudo, recomenda-se sempre dar crédito aos [autores](#autor) originais do conjunto de dados, 
independentemente da sua versão.

## Referências
<!-- ## `dataset_referencia_i` -->

Referência permanente e válida a documentos ou artigos científicos onde a versão original e/ou a versão atual
do conjunto de dados foi usado, preferencialmente, pela primeira vez. Preferência é dada ao uso de um Digital 
Object Identifier ([DOI](https://www.doi.org/)), mas uma URL também é aceita.

Tantas referências quantas forem julgadas pertinentes podem ser inseridas, numerando-as sequencialmente em 
ordem de importância, usando para isso o índice `i`. No caso de os responsáveis atuais pelo conjunto de dados
não serem os seus autores originais, é imprescindível que a referência principal, `i = 1`, seja a um trabalho
dos autores do conjunto de dados. Já a referência secundária, `i = 2`, pode ser a um trabalho dos responsáveis
atuais pelo conjunto de dados. No caso de trabalhos acadêmicos, como monografias, disserações e teses, pode-se
inserir uma referência ao trabalho acadêmico e ao artigo onde o conjunto de dados foi utilizado pela primeira
vez. No caso de o conjunto de dados ter passado por modificações consideráveis, uma referência ao trabalho 
onde a nova versão tenha sido usada pela primeira vez também deve ser inserida. Para inserir novas 
referências, basta inserir, na sequência, novas linhas na tabela `dataset`, usando o `i` para indicar sua
ordem.

## Indexação
<!-- ## `area_conhecimento` -->

Área de especialidade da Agronomia -- Ciência do Solo à qual o conjunto de dados está relacionado. São seis as
áreas de especialidade definidas pelo Conselho Nacional de Desenvolvimento Científico e Tecnológico
([CNPq](http://cnpq.br/documents/10157/186158/TabeladeAreasdoConhecimento.pdf)) e a Coordenação de
Aperfeiçoamento de Pessoal de Nível Superior
([CAPES](http://www.capes.gov.br/avaliacao/instrumentos-de-apoio/tabela-de-areas-do-conhecimento-avaliacao)):

* Gênese, Morfologia e Classificação dos Solos
* Física do Solo
* Química do Solo
* Microbiologia e Bioquímica do Solo
* Fertilidade do Solo e Adubação
* Manejo e Conservação do Solo

<!-- ## `palavras_chave` -->

Lista de termos que descrevem aspectos importantes do conjunto de dados, preferencialmente diferentes daqueles
constantes no título, sendo separados por ponto e vírgula. Uma lista de termos bem elaborada aumenta o 
potencial de descoberta do conjunto de dados por mecanismos de busca.

<!-- ## `categoria_vcge` -->

Categoria do Vocabulário Controlado do Governo Eletrônico ([VCGE](http://vocab.e.gov.br/2011/03/vcge#esquema)).
O VCGE é um esquema padronizado de assuntos e categorias usado para facilitar a apresentação e identificação 
dos serviços disponibilizados em uma estrutura de diretórios *online*. O objetivo do VCGE é ajudar os cidadãos
a encontrar informações em catálogos de dados públicos sem a necessidade de conhecer a organização responsável
pelo assunto ou categoria.
