# Observações no espaço e no tempo

Tabela *observacao*. Nessa tabela são inseridas as informações espaciais mais fundamentais sobre as 
observações do solo.

## Identificação

Identificador exclusivo da observação usado no conjunto de dados de origem (`observacao_id`). Como se trata de
um código, não 
devem ser usados espaços ou caracteres especiais. Espaços são substituídos por um *underscore*, `_`, ou traço,
`-`. Caracteres especiais devem ser substituídos pelo caractere correspondente simplificado, ou seja, `á`
torna-se `a`, `ç` torna-se `c`, e assim por diante. Exemplo: `observacao_id = Perfil-01`.

## Coordenada temporal

Data da observação (`observacao_date`) no formato dd-mm-aaaa. A data de observação é um dos atributos que,
juntamente com as
coordenadas espaciais, definem uma observação em um conjunto de dados. Isso significa que a observação 
repetida, ao longo do tempo, de um mesmo local no espaço, caracteriza a constituição de uma nova observação,
portanto, a definição de uma nova `observacao_id`. O valor padrão, para os casos em que a data de observação é
desconhecida, é `observacao_date = xx-xx-xxxx`. Quando somente o dia e/ou o mês de observação são 
desconhecidos, usa-se o primeiro valor da sequência, ou seja, `dd = 01` e `mm = 01`.

## Coordenadas espaciais

Sistema de referência de coordenadas (SRC) (`coord_sistema`) utilizado para o georreferenciamento das
observações do solo. A
especificação do SRC é fundamental para possibilitar o uso apropriado de dados espaciais, especialmente para 
fins de correlação/cruzamento com outros dados espaciais. Como a especificação do SRC pode ser feita de 
diversas maneiras, são aceitas quaiquer descrições mais populares, não padronizadas, como WGS 84 / UTM zone 
23S. Contudo, para fins de organização dos dados e posterior automatização de processos computacionais, o 
**febr** adota os códigos padronizados e aceitos internacionalmente do European Petroleum Survey Group (EPSG).
Assim, a partir da descrição fornecida com o conjunto de dados, identifica-se o código EPSG correspondente, 
que é usado em substituição daquela.

Coordenada X (`coord_x`) e Y (`coord_y`), ou seja, o mesmo que Longitude e Latitude, desde que em coordenadas
geográficas.

Precisão (`coord_precisao`) com que as coordenadas espaciais foram determinadas (em metros).

`coord_fonte`

Código | Definição
------ | -------------------------------
GPS    | Aparelho GPS
MAPA   | Mapa analógico ou digital
WEB    | Serviço web como o Google Maps

## Localização

Identificação do município (`municipio_id`), estado (`estado_id`) -- ou unidade federativa -- e país 
(`pais_id`) onde a observação foi realizada. Como o **febr**  trata apenas de conjuntos de dados produzidos no
Brasil, usa-se o código ISO 3166-1 alpha-2 do Brasil, ou seja, `BR`. No caso do estado -- ou unidade 
federativa --, usa-se a abreviação da respectiva unidade federativa (UF). O nome do município é escrito por
extenso, conforme encontrado na fonte.

## Amostragem

Tipo de amostragem (`amostra_tipo`). Opções: SIMPLES ou COMPOSTA.

Número de amostras (`amostra_quanti`). Um (1) quando o valor da variável anterior é SIMPLES ou mais para COMPOSTA. Expressar o valor com números inteiros.

Área amostral (m^2^) (`amostra_area`). Por exemplo, a área de uma trincheira costuma ser de 1 m^2^.

<!-- ## `taxon_<sistema>_<ano>`

Identificação do sistema de classificação -- taxonomia -- utilizado para classificar a observação do solo,
incluindo nome e ano, bem a classificação -- táxon -- atribuída à observação, incluíndo nome e sigla. Tanto o
nome como o ano de publicação do sistema de classificação utilizado auxilia na verificação de possíveis
inconsistências na classificação da observação e no processo de harmonização dos dados. O nome da 
classificação atribuída à observação do solo deve ser escrito por extenso, mantendo quaisquer espaços e
caracteres especiais presentes, prefere

Código     | Sistema taxonômico
---------- | -------------------------------------------
fao-unesco | Legend of the World Soil Map
fao-wrb    | World Reference Base for Soil Resources
sibcs      | Sistema Brasileiro de Classificação do Solo
st         | Soil Taxonomy
usc        | Universal Soil Classification

Para os conjuntos de dados que incluem observações do solo classificadas usando dois ou mais sistemas de
classificação, ou diferentes versões do mesmo sistema de classificação, insere-se tantas colunas quantas
forem necessárias.
 -->
