# Amostras de camadas e horizontes {#camadas}

A definição mais recente do que seja o solo estabelece que o mesmo consiste num conjunto de camadas de material mineral e/ou orgânico, geralmente solto, que é afetado por processos físicos, químicos e/ou biológicos na -- ou próximo da -- superfície planetária, e geralmente contém líquidos, gases, e biota e serve de suporte às plantas [@vanEs2017]. A quarta dimensão operacional de um observação do solo, a coordenada vertical *d*, adotada no modelo de dados do **febr**, é de fundamental importância nessa definição. É por meio dela que se descreve a sequência de camadas de material mineral e/ou orgânico que constituem o solo em um determinado local. As amostras obtidas de cada uma dessas camadas, submetidas a análises laboratoriais diversas, permitem conhecer tanto a sua constituição mineral e/ou orgânica, como compreender como são afetadas pelos processos físicos, químicos e/ou biológicos. As informações obtidas nessas análises, as variáveis do solo, são armazenadas no **febr** usando a tabela *camada*. 

Assim como a tabela *observacao*, a tabela *camada* armazena os dados em colunas, e a cada camada de uma observação do solo é dedicada uma linha exclusiva (Tabela \@ref(tab:camadas)). Da mesma forma, não há limites para o número de linhas e colunas na tabela *camada*. Ainda, os mesmos três requerimentos precisam ser atendidos: preenchimento de todas as colunas obrigatórias (destaque em vermelho) e, se possível, das colunas recomendadas (destaque em amarelo); uso de nomeclatura padronizada para as colunas opcionais (destaque em verde); e informação das unidades de medida na segunda linha da tabela. A estrutura da tabela *camada* é descrita nas próximas seções.

```{r, echo=FALSE}
versao <- 
  rbind(
    c("perfil-01", 1, 0, 35, 30),
    c("perfil-01", 2, 35, 86, 29),
    c("perfil-01", 3, 86, 123, 32)
  )
nomes <- paste(
  c("`observacao_id`", "`camada_numero`", "`profund_sup`", "`profund_inf`", "`fe_cloridrico_eaa`"),
  "<br>", c("`#unidade`", "`-`", "`cm`", "`cm`", "`g/kg`"), sep = "")
colnames(versao) <- nomes
pander(versao, caption = "(\\#tab:camadas) Representação da estrutura da tabela *camada*.")
```

## Identificação

`observacao_id`.
Identificador exclusivo da observação usado no conjunto de dados de origem. Refere-se à tabela *observacao*.

`camada_numero`
Número da camada ou horizonte na observação, atribuído consecutivamente de cima para baixo. Há alguma confusão
com essa variável, por vezes sendo atribuído valor numérico sequencial para todo o conjunto de dados. É 
preciso ficar claro que a numeração refere-se à ordem das camadas dentro do perfil à que pertencem, ou seja, a
primeira camada amostrada de um perfil receberá, sempre, o número inteiro 1. O valor padrão, para o caso do
perfil observado possuir apenas uma camada, é `camada_number = 1`.

`camada_nome`
Nome da camada ou horizonte. Exemplo: A, B, C etc. Conjuntos de dados que são produto de trabalhos 
edafológicos raramente terão informações sobre o nome da camada amostrada. Caso essa informação esteja 
presente, deve-se verificar com o responsável pelo conjunto de dados se a informação está correta ou foi 
criada apenas para preencher a coluna da planilha eletrônica. O valor padrão, para o caso do perfil observado
ser oriundo de estudo edafológico, é `camada_nome = NA`.

`amostra_codigo`
Código laboratorial da amostra. Usado para identificar as repetições de laboratório. Alguns grupos de pesquisa
destinam suas amostras para análise em laboratórios especializados, os quais identificam as amostras com 
códigos específicos, que chamamos de `sample_code`. Em outros casos, as análises são feitas pelo laboratório 
do próprio grupo de pesquisa, o qual não necessariamente atribui um código de identificação único às amostras.
Mas esses laboratórios podem realizar as análises com duas ou mais repetições, sendo então o número da 
repetição de uma determinada amostra identificado como `sample_code`. O valor padrão, para o caso em que não 
há código de identificação único e/ou a amostra não foi analisada com repetições, é `amostra_codigo = 1`.

## Coordenadas verticais

Profundidade do limite superior, `profund_sup`, e inferior, `profund_inf`, da camada ou horizonte observados.

## Variáveis

`fe_<extração>_<determinação>`

O valor padrão, para o caso em que o conteúdo de ferro não está disponível, é 
`fe_<extração>_<determinação> = NA`.
